# Generated by Django 4.1.3 on 2023-01-30 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='terminos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos', models.BooleanField(default=False)),
                ('timezone', models.DateTimeField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'terminos',
                'verbose_name_plural': 'terminos',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.IntegerField()),
                ('imglicencia', models.ImageField(upload_to='DRIVE')),
                ('imgantecedentes', models.ImageField(upload_to='DRIVE')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', unique=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='AutoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autos', models.ManyToManyField(to='cars.auto')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
            options={
                'verbose_name': 'AutoDriver',
                'verbose_name_plural': 'AutoDrivers',
            },
        ),
    ]
