# Generated by Django 4.1.3 on 2023-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.IntegerField()),
                ('imglicencia', models.ImageField(upload_to='DRIVE')),
                ('imgantecedentes', models.ImageField(upload_to='DRIVE')),
                ('autos', models.ManyToManyField(to='cars.auto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
