# Generated by Django 4.1.3 on 2022-12-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='imgantecedentes',
            field=models.ImageField(upload_to='DRIVE'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='imglicencia',
            field=models.ImageField(upload_to='DRIVE'),
        ),
    ]
