# Generated by Django 4.1.3 on 2022-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_imgcarro_alter_auto_imgauto_alter_auto_imgsoat'),
        ('drivers', '0002_alter_driver_imgantecedentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='autos',
            field=models.ManyToManyField(to='cars.auto'),
        ),
    ]
