# Generated by Django 4.1.3 on 2023-01-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_terminos_conductor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminos',
            old_name='conductor',
            new_name='persona',
        ),
    ]
