# Generated by Django 4.1.3 on 2023-01-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_auto_imgcarro'),
        ('drivers', '0005_alter_driver_options_alter_terminos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='autos',
        ),
        migrations.CreateModel(
            name='AutoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autos', models.ManyToManyField(to='cars.auto')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
    ]
