# Generated by Django 4.1.3 on 2023-01-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_referido_lazo'),
        ('drivers', '0007_alter_autodriver_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', unique=True),
        ),
    ]
