# Generated by Django 4.1.3 on 2022-12-04 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=300)),
                ('identification', models.IntegerField(verbose_name='cedula')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('O', 'otro')], default='femenino', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to=None)),
                ('tel', models.IntegerField(verbose_name='numero celular')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lazo', models.CharField(choices=[('familiar', 'f'), ('amigo', 'a'), ('conocido', 'c')], default='amigo', max_length=50)),
                ('referidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Referido',
                'verbose_name_plural': 'Referidos',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificaciones', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'calificacion',
                'verbose_name_plural': 'calificaciones',
            },
        ),
    ]
