# Generated by Django 4.1.3 on 2022-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='imgcc',
            field=models.ImageField(blank=True, upload_to='Client', verbose_name='documento de identidad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(upload_to='Client'),
        ),
    ]
