# Generated by Django 4.1.3 on 2023-04-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='usuario',
        ),
    ]
