# Generated by Django 4.1.3 on 2023-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referido',
            name='lazo',
            field=models.CharField(choices=[('f', 'familia'), ('a', 'amigo'), ('c', 'conocido')], default='amigo', max_length=10),
        ),
    ]
