# Generated by Django 4.1.3 on 2022-12-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_imgcc_alter_client_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
    ]
