# Generated by Django 4.1.3 on 2022-12-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_email_alter_client_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField()),
                ('frecarga', models.DateTimeField(verbose_name='fecha recarga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'saldo',
                'verbose_name_plural': 'saldos',
            },
        ),
    ]
