# Generated by Django 4.1.3 on 2022-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldo',
            options={'verbose_name': 'saldo_cliente', 'verbose_name_plural': 'saldos'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
