# Generated by Django 4.1.3 on 2022-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tokenNotifi',
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
    ]
