# Generated by Django 4.1.3 on 2023-01-30 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='contact')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='copyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('url_designed', models.URLField(blank=True, null=True)),
                ('url_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('texto', models.CharField(max_length=30)),
                ('item1', models.CharField(max_length=50)),
                ('item2', models.CharField(max_length=50)),
                ('item3', models.CharField(max_length=50)),
                ('item4', models.CharField(max_length=50)),
                ('item5', models.CharField(max_length=50)),
                ('itemtitle1', models.CharField(max_length=50)),
                ('itemdescription1', models.TextField()),
                ('description', models.TextField()),
                ('itentitle2', models.CharField(max_length=50)),
                ('itemdescription2', models.TextField()),
                ('itemtitle3', models.CharField(max_length=50)),
                ('itemdescription3', models.TextField()),
                ('image1', models.ImageField(upload_to='explore')),
                ('image2', models.ImageField(upload_to='explore')),
            ],
        ),
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlef', models.CharField(max_length=100)),
                ('subtitlef', models.CharField(max_length=150)),
                ('itemtitle1f', models.CharField(max_length=150)),
                ('itemdescription1f', models.TextField()),
                ('itemtitle2f', models.CharField(max_length=150)),
                ('itemdescription2f', models.TextField()),
                ('itemtitle3f', models.CharField(max_length=150)),
                ('itemdescription3f', models.TextField()),
                ('itemtitle4f', models.CharField(max_length=150)),
                ('itemdescription4f', models.TextField()),
                ('itemtitle5f', models.CharField(max_length=150)),
                ('itemdescription5f', models.TextField()),
                ('itemtitle6f', models.CharField(max_length=150)),
                ('itemdescription6f', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('subtitle', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='home')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField()),
                ('itemtitle1', models.CharField(max_length=50)),
                ('itemdescription1', models.TextField()),
                ('itemtitle2', models.CharField(max_length=50)),
                ('itemdescription2', models.TextField()),
                ('itemtitle3', models.CharField(max_length=50)),
                ('itemdescription3', models.TextField()),
                ('itemtitle4', models.CharField(max_length=50)),
                ('itemdescription4', models.TextField()),
                ('itemtitle5', models.CharField(max_length=50)),
                ('itemdescription5', models.TextField()),
                ('itemtitle6', models.CharField(max_length=50)),
                ('itemdescription6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
