# Generated by Django 4.1.3 on 2023-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('item1', models.CharField(max_length=50)),
                ('item2', models.CharField(max_length=50)),
                ('item3', models.CharField(max_length=50)),
                ('item4', models.CharField(max_length=50)),
                ('item5', models.CharField(max_length=50)),
                ('itemtitle1', models.CharField(max_length=50)),
                ('itemdescription1', models.TextField()),
                ('description', models.TextField()),
                ('itentitle2', models.CharField(max_length=50)),
                ('itemdescription2', models.TextField()),
                ('itemtitle3', models.CharField(max_length=50)),
                ('itemdescription3', models.TextField()),
                ('image1', models.ImageField(upload_to='explore')),
                ('image2', models.ImageField(upload_to='explore')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('subtitle', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=50)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='home')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('itemtitle1', models.CharField(max_length=50)),
                ('itemdescription1', models.TextField()),
                ('itemtitle2', models.CharField(max_length=50)),
                ('itemdescription2', models.TextField()),
                ('itemtitle3', models.CharField(max_length=50)),
                ('itemdescription3', models.TextField()),
                ('itemtitle4', models.CharField(max_length=50)),
                ('itemdescription4', models.TextField()),
                ('itemtitle5', models.CharField(max_length=50)),
                ('itemdescription5', models.TextField()),
                ('itemtitle6', models.CharField(max_length=50)),
                ('itemdescription6', models.TextField()),
            ],
        ),
    ]
