# Generated by Django 4.1.3 on 2023-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='texto',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
