# Generated by Django 4.1.3 on 2023-01-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_explore_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
    ]
