# Generated by Django 4.1.3 on 2023-01-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_services_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='about',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='home',
            name='vision',
        ),
    ]
