# Generated by Django 4.1.3 on 2023-01-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_contactform_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='url_designed',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyright',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
