# Generated by Django 4.1.3 on 2023-01-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_copyright_url_designed_copyright_url_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faq',
            new_name='FaqModel',
        ),
    ]
