# Generated by Django 4.1.3 on 2023-01-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_faq_faqmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemdescription1',
            new_name='itemdescription1f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemdescription2',
            new_name='itemdescription2f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemdescription3',
            new_name='itemdescription3f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemdescription4',
            new_name='itemdescription4f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemdescription5',
            new_name='itemdescription5f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemdescription6',
            new_name='itemdescription6f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemtitle1',
            new_name='itemtitle1f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemtitle2',
            new_name='itemtitle2f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemtitle3',
            new_name='itemtitle3f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemtitle4',
            new_name='itemtitle4f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemtitle5',
            new_name='itemtitle5f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='itemtitle6',
            new_name='itemtitle6f',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='subtitle',
            new_name='subtitlef',
        ),
        migrations.RenameField(
            model_name='faqmodel',
            old_name='title',
            new_name='titlef',
        ),
    ]
