# Generated by Django 4.1.3 on 2023-01-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_itemdescription1_faqmodel_itemdescription1f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=models.IntegerField(default=3321151355),
            preserve_default=False,
        ),
    ]
