# Generated by Django 4.1.3 on 2023-01-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_services_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='itemtitle1f',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='itemtitle2f',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='itemtitle3f',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='itemtitle4f',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='itemtitle5f',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='itemtitle6f',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='subtitlef',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='titlef',
            field=models.CharField(max_length=100),
        ),
    ]
