# Generated by Django 4.1.3 on 2023-01-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=50)),
                ('modelo', models.IntegerField()),
                ('imgcarro', models.ImageField(upload_to='car', verbose_name='carro')),
                ('imgsoat', models.ImageField(upload_to='car', verbose_name='soat')),
                ('imgauto', models.ImageField(upload_to='car', verbose_name='foto del auto')),
                ('imgtarjetapropi', models.ImageField(upload_to=None, verbose_name='foto de la tarjeta de propiedad')),
                ('numero_placa', models.CharField(db_index=True, max_length=50)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
            },
        ),
    ]
