# Generated by Django 4.1.3 on 2023-04-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='img_tarjeta_propi',
            field=models.ImageField(upload_to='cars', verbose_name='foto de la tarjeta de propiedad'),
        ),
    ]
