# Generated by Django 4.1.3 on 2023-01-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='color',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='es_propio',
            field=models.BooleanField(default=True),
        ),
    ]
