# Generated by Django 4.1.3 on 2022-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imgcarro',
            field=models.ImageField(default='null', upload_to='car', verbose_name='carro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='imgauto',
            field=models.ImageField(upload_to='car', verbose_name='foto del auto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='imgsoat',
            field=models.ImageField(upload_to='car', verbose_name='soat'),
        ),
    ]
