# Generated by Django 4.1.3 on 2023-01-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_color_auto_es_propio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='imgcarro',
        ),
    ]
