# Generated by Django 4.1.3 on 2022-12-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latori', models.FloatField()),
                ('lngori', models.FloatField()),
                ('latdes', models.FloatField()),
                ('lngdes', models.FloatField()),
                ('distance', models.FloatField()),
                ('testimado', models.CharField(max_length=10)),
                ('tterminado', models.DateTimeField(blank=True, null=True, verbose_name='pedido')),
                ('tpedido', models.DateTimeField(verbose_name='pedido')),
                ('ttake', models.DateTimeField(verbose_name='tomado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
