# Generated by Django 4.1.3 on 2023-01-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppkm', models.FloatField(verbose_name='precio por kilometro')),
                ('ppm', models.FloatField(verbose_name='precio por minuto')),
                ('pm', models.FloatField(verbose_name='precio minimo')),
                ('fechainit', models.DateField(auto_now=True, verbose_name='fecha de implementacion')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latori', models.FloatField()),
                ('lngori', models.FloatField()),
                ('latdes', models.FloatField()),
                ('lngdes', models.FloatField()),
                ('distance', models.FloatField()),
                ('testimado', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('cancelc', models.IntegerField(blank=True, null=True)),
                ('tterminado', models.DateTimeField(blank=True, null=True, verbose_name='terminado')),
                ('tpedido', models.DateTimeField(verbose_name='pedido')),
                ('ttake', models.DateTimeField(verbose_name='tomado')),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('conductor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='clients.client')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='CarrerasNoTomadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_no_tomada', models.DateTimeField(verbose_name='hora no tomada')),
                ('distancia', models.FloatField()),
                ('precio', models.IntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion_origen', models.CharField(max_length=100)),
                ('direccion_destino', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
