# Generated by Django 4.1.3 on 2023-01-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_referido_lazo'),
        ('serveces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoTTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_no_tamada', models.DateTimeField(verbose_name='hora no tomada')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion_origen', models.CharField(max_length=100)),
                ('direccion_destino', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
