# Generated by Django 4.1.3 on 2022-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
