# Generated by Django 4.1.3 on 2023-04-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='recargo_festivo',
            field=models.FloatField(default=0.0, verbose_name='recargo festivo'),
        ),
        migrations.AddField(
            model_name='price',
            name='recargo_nocturno',
            field=models.FloatField(default=0.0, verbose_name='recargo nocturno'),
        ),
    ]
