# Generated by Django 4.1.3 on 2022-12-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0002_services_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tpedido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='ttake',
            field=models.CharField(max_length=50),
        ),
    ]
