# Generated by Django 4.1.3 on 2023-01-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_referido_lazo'),
        ('serveces', '0002_nottake'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoTTake',
            new_name='CarrerasNoTomadas',
        ),
        migrations.RenameField(
            model_name='carrerasnotomadas',
            old_name='hora_no_tamada',
            new_name='hora_no_tomada',
        ),
    ]
