# Generated by Django 4.1.3 on 2023-01-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0003_rename_nottake_carrerasnotomadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrerasnotomadas',
            name='distancia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrerasnotomadas',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
