# Generated by Django 4.1.3 on 2022-12-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0003_alter_services_tpedido_alter_services_ttake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tterminado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
