# Generated by Django 4.1.3 on 2022-12-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0004_alter_services_tterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tpedido',
            field=models.DateTimeField(verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='services',
            name='ttake',
            field=models.DateTimeField(verbose_name='tomado'),
        ),
        migrations.AlterField(
            model_name='services',
            name='tterminado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pedido'),
        ),
    ]
