# Generated by Django 4.1.3 on 2022-12-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0006_services_cancelc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cancelc',
            field=models.CharField(max_length=25),
        ),
    ]
