# Generated by Django 4.1.3 on 2022-12-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0007_alter_services_cancelc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cancelc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
