# Generated by Django 4.1.3 on 2022-12-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0010_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='fechainit',
            field=models.DateField(auto_now=True, verbose_name='fecha de implementacion'),
        ),
    ]
