# Generated by Django 4.1.3 on 2022-12-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_imgantecedentes_and_more'),
        ('clients', '0003_alter_client_email_alter_client_token'),
        ('serveces', '0011_price_fechainit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='services',
            name='conductor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
    ]
