# Generated by Django 4.1.3 on 2022-12-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_email_alter_client_token'),
        ('serveces', '0012_alter_services_client_alter_services_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='conductor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='clients.client'),
        ),
    ]
