# Generated by Django 4.1.3 on 2022-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveces', '0013_alter_services_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tterminado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='terminado'),
        ),
    ]
